const char* AP_SSID = "<WLAN-ESSID>";
const char* AP_PASSWORD = "<WLAN-PASSWORD>";
const char* SERVER_THUMBPRINT = "<SERVER THUMBPRINT>";
const char* ROCKET_CHAT_URL = "<ROCKET CHAT URL>";
const char* ROCKET_CHAT_WEB_HOOK = "<ROCKET CHAT WEB HOOK>";
const char* ROCKET_CHAT_WEB_HOOK_DEBUG = "<ROCKET CHAT WEB HOOK>";
const char* ACTIVATE_TIME = "<START TIME>";
const char* DEACTIVATE_TIME = "<END TIME>";
